api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    path('v1/list/grantgoal/', views.ListGrantGoalAPIView().as_view(), name="list_gg"),
    path('v1/create/grantgoal/', views.CreateGrantGoalAPIView().as_view(), name="create_gg"),
    path('v1/detail/grantgoal/<int:pk>/', views.DetailGrantGoalAPIView().as_view(), name="detail_gg"),
    path('v1/update/grantgoal/<int:pk>/', views.UpdateGrantGoalAPIView().as_view(), name="update_gg"),
    path('v1/delete/grantgoal/<int:pk>/', views.DeleteGrantGoalAPIView().as_view(), name="delete_gg"),
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"


urlpatterns = [
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="list_gg"),
    path('create/grantgoal/', views.CreateGrantGoal.as_view(), name="create_gg"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_gg"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_gg"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_gg"),
]

plaesem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('client/', include("apiclients.urls")),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class Area(models.Model):
    area_name = models.CharField(max_length=64, default="Generic Area")
    timestamp = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.area_name



CHOICES_STATE = (
    ("Done", "DN"),
    ("Doing", "DG"),
    ("Not Stared", "NS"),
)

class GrantGoal(models.Model):
    gg_name = models.CharField(max_length=128, default="Generic Grant Goal")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=256, default="Generic Grant Goal Description")
    days_durations = models.IntegerField(default=7)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    final_date = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    progress = models.FloatField(default=0.0)
    state = models.CharField(max_length=16, choices=CHOICES_STATE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.gg_name
    

@receiver(post_save, sender=GrantGoal)
def final_date_grantgoal(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_durations)
        instance.save()



class SubGrantGoal(models.Model):
    sgg_name = models.CharField(max_length=128, default="Generic Grant Goal")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    grant_goal = models.ForeignKey(GrantGoal, on_delete=models.CASCADE)
    description = models.CharField(max_length=256, default="Generic Grant Goal Description")
    days_durations = models.IntegerField(default=7)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    final_date = models.DateField(auto_now_add=False, auto_now=True)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    progress = models.FloatField(default=0.0)
    state = models.CharField(max_length=16, choices=CHOICES_STATE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.sgg_name


@receiver(post_save, sender=SubGrantGoal)
def final_date_subgrantgoal(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_durations)
        instance.save()
    

class Goal(models.Model):
    goal_name = models.CharField(max_length=128, default="Generic Grant Goal")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subgrant_goal = models.ForeignKey(SubGrantGoal, on_delete=models.CASCADE)
    description = models.CharField(max_length=256, default="Generic Grant Goal Description")
    days_durations = models.IntegerField(default=7)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    final_date = models.DateField(auto_now_add=False, auto_now=True)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    progress = models.FloatField(default=0.0)
    state = models.CharField(max_length=16, choices=CHOICES_STATE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.goal_name
    

@receiver(post_save, sender=Goal)
def final_date_goal(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_durations)
        instance.save()


class Issue(models.Model):
    issue_name = models.CharField(max_length=128, default="Generic Grant Goal")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    goal = models.ForeignKey(Goal, on_delete=models.CASCADE)
    description = models.CharField(max_length=256, default="Generic Grant Goal Description")
    days_durations = models.IntegerField(default=7)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    final_date = models.DateField(auto_now_add=False, auto_now=True)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    progress = models.FloatField(default=0.0)
    state = models.CharField(max_length=16, choices=CHOICES_STATE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.issue_name


@receiver(post_save, sender=Issue)
def final_date_issue(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_durations)
        instance.save()

core/forms.py
from django import forms

from core import models


class CreateGrantGoalForm(forms.ModelForm):
    class Meta:
        model = models.GrantGoal
        exclude = [
            "timestamp",
            "final_date",
            "status"
        ]
        widgets = {
            "gg_name": forms.TextInput({"type": "text", "class": "form-control", "placeholder": "Escribe el nombre del GrantGoal"}),
            "user": forms.Select({"type": "select", "class": "form-select"}),
            "description": forms.Textarea({"type": "text", "class": "form-control", "rows": 3}),
            "days_durations": forms.NumberInput({"type": "number", "class": "form-control"}),
            "area": forms.Select({"type": "select", "class": "form-select"}),
            "progress": forms.NumberInput({"type": "number", "class": "form-control"}),
            "state": forms.Select({"type": "select", "class": "form-select"}),
            "slug": forms.TextInput({"type": "text", "class": "form-control", "placeholder": "Escribe el codigo del GrantGoal"}),
        }


class UpdateGrantGoalForm(forms.ModelForm):
    class Meta:
        model = models.GrantGoal
        exclude = [
            "timestamp",
            "final_date",
           
        ]
        widgets = {
            "gg_name": forms.TextInput({"type": "text", "class": "form-control", "placeholder": "Escribe el nombre del GrantGoal"}),
            "user": forms.Select({"type": "select", "class": "form-select"}),
            "description": forms.Textarea({"type": "text", "class": "form-control", "rows": 3}),
            "days_durations": forms.NumberInput({"type": "number", "class": "form-control"}),
            "area": forms.Select({"type": "select", "class": "form-select"}),
            "progress": forms.NumberInput({"type": "number", "class": "form-control"}),
            "state": forms.Select({"type": "select", "class": "form-select"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox", "class":"form-checkbox"}),
            "slug": forms.TextInput({"type": "text", "class": "form-control", "placeholder": "Escribe el codigo del GrantGoal"}),
        }
        

core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin

from core import models
from core import forms

# Create your views here.


##### GRANT GOAL CRUD #####

### CREATE
class CreateGrantGoal(LoginRequiredMixin, generic.CreateView):
    template_name = "core/create_gg.html"
    model = models.GrantGoal
    form_class = forms.CreateGrantGoalForm
    success_url = reverse_lazy("core:list_gg")
    login_url = "home:index"


### RETRIEVE
# List
class ListGrantGoal(generic.View):
    template_name = "core/list_gg.html"
    context = {}

    def get(self, request):
        self.context = {
            "grant_goals": models.GrantGoal.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)


# Detail
class DetailGrantGoal(generic.View):
    template_name = "core/detail_gg.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "grant_goal": models.GrantGoal.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)


### UPDATE
class UpdateGrantGoal(generic.UpdateView):
    template_name = "core/update_gg.html"
    model = models.GrantGoal
    form_class = forms.UpdateGrantGoalForm
    success_url = reverse_lazy("core:list_gg")

### DELETE
class DeleteGrantGoal(generic.DeleteView):
    template_name = "core/delete_gg.html"
    model = models.GrantGoal
    success_url = reverse_lazy("core:list_gg")



##### SUBGRANT GOAL CRUD #####
### CREATE
### RETRIEVE
## List
## Detail
### UPDATE
### DELETE


##### GOAL CRUD #####
### CREATE
### RETRIEVE
## List
## Detail
### UPDATE
### DELETE


##### ISSUE CRUD #####
### CREATE
### RETRIEVE
## List
## Detail
### UPDATE
### DELETE


##### AREA CRUD #####
### CREATE
### RETRIEVE
## List
## Detail
### UPDATE
### DELETE

templates/core/create_gg.html
{% extends "base/base.html" %}

{% block title %}CREATE GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
            {{ form }}
            <hr>
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-outline-success form-control">Create New GrantGoal</button>
                </div>
                <div class="col">
                    <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning form-control">Cancel</a>
                </div>
            </div>
    </form>
{% endblock content %}

templates/core/delete_gg.html
{% extends "base/base.html" %}

{% block title %}DELETE GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
           <h2>¿Realmente deseas eliminar al GrantGoal " {{ object }}"?</h2>
            <hr>
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-outline-danger form-control">Delete GrantGoal</button>
                </div>
                <div class="col">
                    <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning form-control">Cancel</a>
                </div>
            </div>
    </form>
{% endblock content %}

templates/core/detail_gg.html
{% extends "base/base.html" %}

{% block title %}DETAIL GRANT GOAL VIEW{% endblock title %}

{% block content %}

<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
         General Data
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the " {{ grant_goal.gg_name }} " grant goal name.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          State Data
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
        </div>
      </div>
    </div>
  </div>
    
    <hr>
    <a href="{% url 'core:list_gg' %}" class="btn btn-link">Return</a>
{% endblock content %}

templates/core/list_gg.html
{% extends "base/base.html" %}

{% block title %}LIST GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <hr>
        <a href="{% url 'core:create_gg' %}" class="btn btn-outline-success">CREATE NEW GRANT GOAL</a>
       
    <hr>
    <table class="table table-striped">
        <thead>
            <th>Id</th>
            <th>Name</th>
            <th>User</th>
            <th>timestamp</th>
            <th>status</th>
            <th></th>
            <th>Actions</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in grant_goals %}
                <tr>
                    <td>{{ gg.id }}</td>
                    <td>{{ gg.gg_name }}</td>
                    <td>{{ gg.user }}</td>
                    <td>{{ gg.timestamp }}</td>
                    <td>{{ gg.status }}</td>
                    <td><a href="{% url 'core:detail_gg' gg.pk %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'core:update_gg' gg.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_gg' gg.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor%}
        </tbody>
    </table>
{% endblock content %}

templates/core/update_gg.html
{% extends "base/base.html" %}

{% block title %}UPDATE GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
            {{ form }}
            <hr>
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-outline-success form-control">Update GrantGoal</button>
                </div>
                <div class="col">
                    <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning form-control">Cancel</a>
                </div>
            </div>
    </form>
{% endblock content %}